version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: edumeet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
# alter user 'root'@'%' identified with mysql_native_password by 'root';
